/*
 * Copyright (c) 2014 DeNA Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the &quot;Software&quot;), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

/* automatically generated by tokens.pl */

static const struct st_h2o_hpack_static_table_entry_t h2o_hpack_static_table[61] = {
    {H2O_TOKEN_AUTHORITY, {H2O_STRLIT("")}},
    {H2O_TOKEN_METHOD, {H2O_STRLIT("GET")}},
    {H2O_TOKEN_METHOD, {H2O_STRLIT("POST")}},
    {H2O_TOKEN_PATH, {H2O_STRLIT("/")}},
    {H2O_TOKEN_PATH, {H2O_STRLIT("/index.html")}},
    {H2O_TOKEN_SCHEME, {H2O_STRLIT("http")}},
    {H2O_TOKEN_SCHEME, {H2O_STRLIT("https")}},
    {H2O_TOKEN_STATUS, {H2O_STRLIT("200")}},
    {H2O_TOKEN_STATUS, {H2O_STRLIT("204")}},
    {H2O_TOKEN_STATUS, {H2O_STRLIT("206")}},
    {H2O_TOKEN_STATUS, {H2O_STRLIT("304")}},
    {H2O_TOKEN_STATUS, {H2O_STRLIT("400")}},
    {H2O_TOKEN_STATUS, {H2O_STRLIT("404")}},
    {H2O_TOKEN_STATUS, {H2O_STRLIT("500")}},
    {H2O_TOKEN_ACCEPT_CHARSET, {H2O_STRLIT("")}},
    {H2O_TOKEN_ACCEPT_ENCODING, {H2O_STRLIT("gzip, deflate")}},
    {H2O_TOKEN_ACCEPT_LANGUAGE, {H2O_STRLIT("")}},
    {H2O_TOKEN_ACCEPT_RANGES, {H2O_STRLIT("")}},
    {H2O_TOKEN_ACCEPT, {H2O_STRLIT("")}},
    {H2O_TOKEN_ACCESS_CONTROL_ALLOW_ORIGIN, {H2O_STRLIT("")}},
    {H2O_TOKEN_AGE, {H2O_STRLIT("")}},
    {H2O_TOKEN_ALLOW, {H2O_STRLIT("")}},
    {H2O_TOKEN_AUTHORIZATION, {H2O_STRLIT("")}},
    {H2O_TOKEN_CACHE_CONTROL, {H2O_STRLIT("")}},
    {H2O_TOKEN_CONTENT_DISPOSITION, {H2O_STRLIT("")}},
    {H2O_TOKEN_CONTENT_ENCODING, {H2O_STRLIT("")}},
    {H2O_TOKEN_CONTENT_LANGUAGE, {H2O_STRLIT("")}},
    {H2O_TOKEN_CONTENT_LENGTH, {H2O_STRLIT("")}},
    {H2O_TOKEN_CONTENT_LOCATION, {H2O_STRLIT("")}},
    {H2O_TOKEN_CONTENT_RANGE, {H2O_STRLIT("")}},
    {H2O_TOKEN_CONTENT_TYPE, {H2O_STRLIT("")}},
    {H2O_TOKEN_COOKIE, {H2O_STRLIT("")}},
    {H2O_TOKEN_DATE, {H2O_STRLIT("")}},
    {H2O_TOKEN_ETAG, {H2O_STRLIT("")}},
    {H2O_TOKEN_EXPECT, {H2O_STRLIT("")}},
    {H2O_TOKEN_EXPIRES, {H2O_STRLIT("")}},
    {H2O_TOKEN_FROM, {H2O_STRLIT("")}},
    {H2O_TOKEN_HOST, {H2O_STRLIT("")}},
    {H2O_TOKEN_IF_MATCH, {H2O_STRLIT("")}},
    {H2O_TOKEN_IF_MODIFIED_SINCE, {H2O_STRLIT("")}},
    {H2O_TOKEN_IF_NONE_MATCH, {H2O_STRLIT("")}},
    {H2O_TOKEN_IF_RANGE, {H2O_STRLIT("")}},
    {H2O_TOKEN_IF_UNMODIFIED_SINCE, {H2O_STRLIT("")}},
    {H2O_TOKEN_LAST_MODIFIED, {H2O_STRLIT("")}},
    {H2O_TOKEN_LINK, {H2O_STRLIT("")}},
    {H2O_TOKEN_LOCATION, {H2O_STRLIT("")}},
    {H2O_TOKEN_MAX_FORWARDS, {H2O_STRLIT("")}},
    {H2O_TOKEN_PROXY_AUTHENTICATE, {H2O_STRLIT("")}},
    {H2O_TOKEN_PROXY_AUTHORIZATION, {H2O_STRLIT("")}},
    {H2O_TOKEN_RANGE, {H2O_STRLIT("")}},
    {H2O_TOKEN_REFERER, {H2O_STRLIT("")}},
    {H2O_TOKEN_REFRESH, {H2O_STRLIT("")}},
    {H2O_TOKEN_RETRY_AFTER, {H2O_STRLIT("")}},
    {H2O_TOKEN_SERVER, {H2O_STRLIT("")}},
    {H2O_TOKEN_SET_COOKIE, {H2O_STRLIT("")}},
    {H2O_TOKEN_STRICT_TRANSPORT_SECURITY, {H2O_STRLIT("")}},
    {H2O_TOKEN_TRANSFER_ENCODING, {H2O_STRLIT("")}},
    {H2O_TOKEN_USER_AGENT, {H2O_STRLIT("")}},
    {H2O_TOKEN_VARY, {H2O_STRLIT("")}},
    {H2O_TOKEN_VIA, {H2O_STRLIT("")}},
    {H2O_TOKEN_WWW_AUTHENTICATE, {H2O_STRLIT("")}}};
