.TH H2O 8
.SH NAME
h2o \- the optimized HTTP/1.x, HTTP/2 server
.SH SYNOPSIS
.B h2o
[\fB\-c,\-\-conf\fR \fIFILE\fR]
[\fB\-m,\-\-mode\fR \fIworker|daemon|master|tests\fR]
[\fB\-v,\-\-version]
[\fB\-h,\-\-help]
.SH DESCRIPTION
.B h2o
The optimized HTTP/1.x, HTTP/2 server
.SH OPTIONS
.TP
.BR \-c ", " \-\-conf =\fIFILE\fR
configuration file (default: h2o.conf)
.TP
.BR \-m ", " \-\-mode =\fI<worker>\fR
 Where <worker> specifies one of the following mode:
.RS
.RS
.PP
-
.B worker
: invoked process handles incoming connections (default)
.PP
-
.B daemon
: spawns a master process and exits. `error-log` must be configured when using this mode, as all the errors are logged to the file instead of being emitted to STDERR
.PP
-
.B master
: invoked process becomes a master process (using the `share/h2o/start_server` command) and spawns a worker process for handling incoming connections. Users may send SIGHUP to the master process to reconfigure or upgrade the server.
.PP
-
.B test
: tests the configuration
.RE
.RE
.TP
.BR \-t ", " \-\-test
synonym of `--mode=test`
.TP
.BR \-v ", " \-\-version
prints the version number
.TP
.BR \-h ", " \-\-help
print this help
.SH SEE ALSO
h2o.conf(5)
