.Dd $Mdocdate: July 17 2014 $
.Dt ASN1_STRING_NEW 3
.Os
.Sh NAME
.Nm ASN1_STRING_new ,
.Nm ASN1_STRING_type_new ,
.Nm ASN1_STRING_free
.Nd ASN1_STRING allocation functions
.Sh SYNOPSIS
.In openssl/asn1.h
.Ft ASN1_STRING *
.Fo ASN1_STRING_new
.Fa void
.Fc
.Ft ASN1_STRING *
.Fo ASN1_STRING_type_new
.Fa "int type"
.Fc
.Ft void
.Fo ASN1_STRING_free
.Fa "ASN1_STRING *a"
.Fc
.Sh DESCRIPTION
.Fn ASN1_STRING_new
returns an allocated
.Vt ASN1_STRING
structure.
Its type is undefined.
.Pp
.Fn ASN1_STRING_type_new
returns an allocated
.Vt ASN1_STRING
structure of type
.Fa type .
.Pp
.Fn ASN1_STRING_free
frees up
.Fa a .
.Sh NOTES
Other string types call the ASN1_STRING functions.
For example
.Fn ASN1_OCTET_STRING_new
calls
.Fn ASN1_STRING_type V_ASN1_OCTET_STRING .
.Sh RETURN VALUES
.Fn ASN1_STRING_new
and
.Fn ASN1_STRING_type_new
return a valid
.Vt ASN1_STRING
structure or
.Dv NULL
if an error occurred.
.Pp
.Fn ASN1_STRING_free
does not return a value.
.Sh SEE ALSO
.Xr ERR_get_error 3
