.\"
.\"	$OpenBSD$
.\"
.Dd $Mdocdate: October 12 2014 $
.Dt SSL_GET_RBIO 3
.Os
.Sh NAME
.Nm SSL_get_rbio ,
.Nm SSL_get_wbio
.Nd get BIO linked to an SSL object
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft BIO *
.Fn SSL_get_rbio "SSL *ssl"
.Ft BIO *
.Fn SSL_get_wbio "SSL *ssl"
.Sh DESCRIPTION
.Fn SSL_get_rbio
and
.Fn SSL_get_wbio
return pointers to the
.Vt BIO Ns s
for the read or the write channel, which can be different.
The reference count of the
.Vt BIO
is not incremented.
.Sh RETURN VALUES
The following return values can occur:
.Bl -tag -width Ds
.It Dv NULL
No
.Vt BIO
was connected to the
.Vt SSL
object.
.It Any other pointer
The
.Vt BIO
linked to
.Fa ssl .
.El
.Sh SEE ALSO
.Xr bio 3 ,
.Xr ssl 3 ,
.Xr SSL_set_bio 3
