.\"
.\"	$OpenBSD$
.\"
.Dd $Mdocdate: October 12 2014 $
.Dt SSL_NEW 3
.Os
.Sh NAME
.Nm SSL_new
.Nd create a new SSL structure for a connection
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft SSL *
.Fn SSL_new "SSL_CTX *ctx"
.Sh DESCRIPTION
.Fn SSL_new
creates a new
.Vt SSL
structure which is needed to hold the data for a TLS/SSL connection.
The new structure inherits the settings of the underlying context
.Fa ctx :
connection method (SSLv2/v3/TLSv1), options, verification settings,
timeout settings.
.Sh RETURN VALUES
The following return values can occur:
.Bl -tag -width Ds
.It Dv NULL
The creation of a new
.Vt SSL
structure failed.
Check the error stack to find out the reason.
.It Pointer to an Vt SSL No structure
The return value points to an allocated
.Vt SSL
structure.
.El
.Sh SEE ALSO
.Xr ssl 3 ,
.Xr SSL_clear 3 ,
.Xr SSL_CTX_set_options 3 ,
.Xr SSL_free 3 ,
.Xr SSL_get_SSL_CTX 3
