/*
 * Copyright (c) 2014 DeNA Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the &quot;Software&quot;), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

/* DO NOT EDIT! generated by tokens.pl */
#ifndef h2o__token_h
#define h2o__token_h

#define H2O_TOKEN_AUTHORITY (h2o__tokens + 0)
#define H2O_TOKEN_METHOD (h2o__tokens + 1)
#define H2O_TOKEN_PATH (h2o__tokens + 2)
#define H2O_TOKEN_SCHEME (h2o__tokens + 3)
#define H2O_TOKEN_STATUS (h2o__tokens + 4)
#define H2O_TOKEN_ACCEPT (h2o__tokens + 5)
#define H2O_TOKEN_ACCEPT_CHARSET (h2o__tokens + 6)
#define H2O_TOKEN_ACCEPT_ENCODING (h2o__tokens + 7)
#define H2O_TOKEN_ACCEPT_LANGUAGE (h2o__tokens + 8)
#define H2O_TOKEN_ACCEPT_RANGES (h2o__tokens + 9)
#define H2O_TOKEN_ACCESS_CONTROL_ALLOW_ORIGIN (h2o__tokens + 10)
#define H2O_TOKEN_AGE (h2o__tokens + 11)
#define H2O_TOKEN_ALLOW (h2o__tokens + 12)
#define H2O_TOKEN_AUTHORIZATION (h2o__tokens + 13)
#define H2O_TOKEN_CACHE_CONTROL (h2o__tokens + 14)
#define H2O_TOKEN_CACHE_DIGEST (h2o__tokens + 15)
#define H2O_TOKEN_CONNECTION (h2o__tokens + 16)
#define H2O_TOKEN_CONTENT_DISPOSITION (h2o__tokens + 17)
#define H2O_TOKEN_CONTENT_ENCODING (h2o__tokens + 18)
#define H2O_TOKEN_CONTENT_LANGUAGE (h2o__tokens + 19)
#define H2O_TOKEN_CONTENT_LENGTH (h2o__tokens + 20)
#define H2O_TOKEN_CONTENT_LOCATION (h2o__tokens + 21)
#define H2O_TOKEN_CONTENT_RANGE (h2o__tokens + 22)
#define H2O_TOKEN_CONTENT_TYPE (h2o__tokens + 23)
#define H2O_TOKEN_COOKIE (h2o__tokens + 24)
#define H2O_TOKEN_DATE (h2o__tokens + 25)
#define H2O_TOKEN_ETAG (h2o__tokens + 26)
#define H2O_TOKEN_EXPECT (h2o__tokens + 27)
#define H2O_TOKEN_EXPIRES (h2o__tokens + 28)
#define H2O_TOKEN_FROM (h2o__tokens + 29)
#define H2O_TOKEN_HOST (h2o__tokens + 30)
#define H2O_TOKEN_HTTP2_SETTINGS (h2o__tokens + 31)
#define H2O_TOKEN_IF_MATCH (h2o__tokens + 32)
#define H2O_TOKEN_IF_MODIFIED_SINCE (h2o__tokens + 33)
#define H2O_TOKEN_IF_NONE_MATCH (h2o__tokens + 34)
#define H2O_TOKEN_IF_RANGE (h2o__tokens + 35)
#define H2O_TOKEN_IF_UNMODIFIED_SINCE (h2o__tokens + 36)
#define H2O_TOKEN_KEEP_ALIVE (h2o__tokens + 37)
#define H2O_TOKEN_LAST_MODIFIED (h2o__tokens + 38)
#define H2O_TOKEN_LINK (h2o__tokens + 39)
#define H2O_TOKEN_LOCATION (h2o__tokens + 40)
#define H2O_TOKEN_MAX_FORWARDS (h2o__tokens + 41)
#define H2O_TOKEN_PROXY_AUTHENTICATE (h2o__tokens + 42)
#define H2O_TOKEN_PROXY_AUTHORIZATION (h2o__tokens + 43)
#define H2O_TOKEN_RANGE (h2o__tokens + 44)
#define H2O_TOKEN_REFERER (h2o__tokens + 45)
#define H2O_TOKEN_REFRESH (h2o__tokens + 46)
#define H2O_TOKEN_RETRY_AFTER (h2o__tokens + 47)
#define H2O_TOKEN_SERVER (h2o__tokens + 48)
#define H2O_TOKEN_SET_COOKIE (h2o__tokens + 49)
#define H2O_TOKEN_STRICT_TRANSPORT_SECURITY (h2o__tokens + 50)
#define H2O_TOKEN_TE (h2o__tokens + 51)
#define H2O_TOKEN_TRANSFER_ENCODING (h2o__tokens + 52)
#define H2O_TOKEN_UPGRADE (h2o__tokens + 53)
#define H2O_TOKEN_USER_AGENT (h2o__tokens + 54)
#define H2O_TOKEN_VARY (h2o__tokens + 55)
#define H2O_TOKEN_VIA (h2o__tokens + 56)
#define H2O_TOKEN_WWW_AUTHENTICATE (h2o__tokens + 57)
#define H2O_TOKEN_X_COMPRESS_HINT (h2o__tokens + 58)
#define H2O_TOKEN_X_FORWARDED_FOR (h2o__tokens + 59)
#define H2O_TOKEN_X_REPROXY_URL (h2o__tokens + 60)
#define H2O_TOKEN_X_TRAFFIC (h2o__tokens + 61)

#endif
