.Dd $Mdocdate: July 17 2014 $
.Dt BIO_S_NULL 3
.Os
.Sh NAME
.Nm BIO_s_null
.Nd null data sink
.Sh SYNOPSIS
.In openssl/bio.h
.Ft BIO_METHOD *
.Fo BIO_s_null
.Fa void
.Fc
.Sh DESCRIPTION
.Fn BIO_s_null
returns the null sink BIO method.
Data written to the null sink is discarded, reads return EOF.
.Sh NOTES
A null sink BIO behaves in a similar manner to the
.Xr null 4
device.
.Pp
A null bio can be placed on the end of a chain to discard any data
passed through it.
.Pp
A null sink is useful if, for example, an application wishes
to digest some data by writing through a digest bio
but not send the digested data anywhere.
Since a BIO chain must normally include a source/sink BIO,
this can be achieved by adding a null sink BIO to the end of the chain.
.Sh RETURN VALUES
.Fn BIO_s_null
returns the null sink BIO method.
