.Dd $Mdocdate: July 17 2014 $
.Dt BIO_F_NULL 3
.Os
.Sh NAME
.Nm BIO_f_null
.Nd null filter
.Sh SYNOPSIS
.In openssl/bio.h
.Ft BIO_METHOD *
.Fo BIO_f_null
.Fa void
.Fc
.Sh DESCRIPTION
.Fn BIO_f_null
returns the null filter BIO method.
This is a filter BIO that does nothing.
.Pp
All requests to a null filter BIO are passed through to the next BIO
in the chain: this means that a BIO chain containing a null filter BIO
behaves just as though the BIO was not there.
.Sh NOTES
As may be apparent, a null filter BIO is not particularly useful.
.Sh RETURN VALUES
.Fn BIO_f_null
returns the null filter BIO method.
