.Dd $Mdocdate: March 21 2015 $
.Dt CMS_GET0_TYPE 3
.Os
.Sh NAME
.Nm CMS_get0_type ,
.Nm CMS_set1_eContentType ,
.Nm CMS_get0_eContentType
.Nd get and set CMS content types
.Sh SYNOPSIS
.In openssl/cms.h
.Ft const ASN1_OBJECT *
.Fo CMS_get0_type
.Fa "CMS_ContentInfo *cms"
.Fc
.Ft int
.Fo CMS_set1_eContentType
.Fa "CMS_ContentInfo *cms"
.Fa "const ASN1_OBJECT *oid"
.Fc
.Ft const ASN1_OBJECT *
.Fo CMS_get0_eContentType
.Fa "CMS_ContentInfo *cms"
.Fc
.Sh DESCRIPTION
.Fn CMS_get0_type
returns the content type of a
.Vt CMS_ContentInfo
structure as an
.Vt ASN1_OBJECT
pointer.
An application can then decide how to process the
.Vt CMS_ContentInfo
structure based on this value.
.Pp
.Fn CMS_set1_eContentType
sets the embedded content type of a
.Vt CMS_ContentInfo
structure.
It should be called with CMS functions with the
.Dv CMS_PARTIAL
flag and
.Em before
the structure is finalised, otherwise the results are undefined.
.Pp
.Fn CMS_get0_eContentType
returns a pointer to the embedded content type.
.Sh NOTES
As the
.Sq 0
implies,
.Fn CMS_get0_type
and
.Fn CMS_get0_eContentType
return internal pointers which should
.Em not
be freed up.
.Fn CMS_set1_eContentType
copies the supplied OID and it
.Em should
be freed up after use.
.Pp
The
.Vt ASN1_OBJECT
values returned can be converted to an integer NID value using
.Xr OBJ_obj2nid 3 .
For the currently supported content types the following values are
returned:
.Bd -unfilled -offset indent
.Dv NID_pkcs7_data
.Dv NID_pkcs7_signed
.Dv NID_pkcs7_digest
.Dv NID_id_smime_ct_compressedData
.Dv NID_pkcs7_encrypted
.Dv NID_pkcs7_enveloped
.Ed
.Sh RETURN VALUES
.Fn CMS_get0_type
and
.Fn CMS_get0_eContentType
return an
.Vt ASN1_OBJECT
structure.
.Pp
.Fn CMS_set1_eContentType
returns 1 for success or 0 if an error occurred.
The error can be obtained from
.Xr ERR_get_error 3 .
.Sh SEE ALSO
.Xr ERR_get_error 3
.Sh HISTORY
.Fn CMS_get0_type ,
.Fn CMS_set1_eContentType ,
and
.Fn CMS_get0_eContentType
were all first added to OpenSSL 0.9.8.
