.\"
.\"	$OpenBSD$
.\"
.Dd $Mdocdate: October 12 2014 $
.Dt SSL_GET_DEFAULT_TIMEOUT 3
.Os
.Sh NAME
.Nm SSL_get_default_timeout
.Nd get default session timeout value
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft long
.Fn SSL_get_default_timeout "const SSL *ssl"
.Sh DESCRIPTION
.Fn SSL_get_default_timeout
returns the default timeout value assigned to
.Vt SSL_SESSION
objects negotiated for the protocol valid for
.Fa ssl .
.Sh NOTES
Whenever a new session is negotiated, it is assigned a timeout value,
after which it will not be accepted for session reuse.
If the timeout value was not explicitly set using
.Xr SSL_CTX_set_timeout 3 ,
the hardcoded default timeout for the protocol will be used.
.Pp
.Fn SSL_get_default_timeout
return this hardcoded value, which is 300 seconds for all currently supported
protocols (SSLv2, SSLv3, and TLSv1).
.Sh RETURN VALUES
See description.
.Sh SEE ALSO
.Xr ssl 3 ,
.Xr SSL_CTX_flush_sessions 3 ,
.Xr SSL_CTX_set_session_cache_mode 3 ,
.Xr SSL_SESSION_get_time 3
