.\"
.\"	$OpenBSD$
.\"
.Dd $Mdocdate: October 12 2014 $
.Dt SSL_CTX_ADD_EXTRA_CHAIN_CERT 3
.Os
.Sh NAME
.Nm SSL_CTX_add_extra_chain_cert
.Nd add certificate to chain
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft long
.Fn SSL_CTX_add_extra_chain_cert "SSL_CTX ctx" "X509 *x509"
.Sh DESCRIPTION
.Fn SSL_CTX_add_extra_chain_cert
adds the certificate
.Fa x509
to the certificate chain presented together with the certificate.
Several certificates can be added one after the other.
.Sh NOTES
When constructing the certificate chain, the chain will be formed from
these certificates explicitly specified.
If no chain is specified, the library will try to complete the chain from the
available CA certificates in the trusted CA storage, see
.Xr SSL_CTX_load_verify_locations 3 .
.Pp
The x509 certificate provided to
.Fn SSL_CTX_add_extra_chain_cert
will be freed by the library when the
.Vt SSL_CTX
is destroyed.
An application
.Em should not
free the
.Fa x509
object.
.Sh RETURN VALUES
.Fn SSL_CTX_add_extra_chain_cert
returns 1 on success.
Check out the error stack to find out the reason for failure otherwise.
.Sh SEE ALSO
.Xr ssl 3 ,
.Xr SSL_CTX_load_verify_locations 3 ,
.Xr SSL_CTX_set_client_cert_cb 3 ,
.Xr SSL_CTX_use_certificate 3
