.\"
.\"	$OpenBSD$
.\"
.Dd $Mdocdate: October 12 2014 $
.Dt SSL_GET_PSK_IDENTITY 3
.Os
.Sh NAME
.Nm SSL_get_psk_identity ,
.Nm SSL_get_psk_identity_hint
.Nd get PSK client identity and hint
.Sh SYNOPSIS
.In openssl/ssl.h
.Ft const char *
.Fn SSL_get_psk_identity_hint "const SSL *ssl"
.Ft const char *
.Fn SSL_get_psk_identity "const SSL *ssl"
.Sh DESCRIPTION
.Fn SSL_get_psk_identity_hint
is used to retrieve the PSK identity hint used during the connection setup
related to
.Vt SSL
object
.Fa ssl .
Similarly,
.Fn SSL_get_psk_identity
is used to retrieve the PSK identity used during the connection setup.
.Sh RETURN VALUES
If
.Pf non- Dv NULL ,
.Fn SSL_get_psk_identity_hint
returns the PSK identity hint and
.Fn SSL_get_psk_identity
returns the PSK identity.
Both are
.Dv NULL Ns -terminated.
.Fn SSL_get_psk_identity_hint
may return
.Dv NULL
if no PSK identity hint was used during the connection setup.
.Pp
Note that the return value is valid only during the lifetime of the
.Vt SSL
object
.Fa ssl .
