#! /bin/sh
export INSTALL_DIR=${HOME}/local
export CPANM_DIR=${HOME}/cpanm
export PATH=$(misc/travis/insert_path.pl ${INSTALL_DIR}/bin ${CPANM_DIR}/bin)
export PKG_CONFIG_PATH=${INSTALL_DIR}/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig
export PERL5LIB=${CPANM_DIR}/lib/perl5
export PERL_CPANM_OPT="--local-lib=${CPANM_DIR}"
export PERL_MB_OPT="--install_base ${CPANM_DIR}"
export PERL_MM_OPT="INSTALL_BASE=${CPANM_DIR}"
