#!/bin/sh

# This file exists for backwards-compatibility with build systems that expect a
# config script similar to OpenSSL's.

# New software should prefer the native configure script over this one.

ARGS=""
for var in "$@"; do
	case $var in
		no-shared ) ARGS="$ARGS --disable-shared";;
		no-asm    ) ARGS="$ARGS --disable-asm";;
		--prefix* ) ARGS="$ARGS $var";;
	esac
done

./configure $ARGS
